// Command docgen renders vexillum's command reference from the registry in
// internal/cli, so the docs can't drift from the CLI.
//
// It is a dev-only tool, like tools/whiteboard-bundle: run it by hand when a
// command changes, never as part of the installed binary. It writes:
//
//   - site/content/docs/reference/cli/<command>.mdx, one page per command
//     (usage verbatim in a code block), plus an index.mdx, and
//   - the command table in README.md, between the docgen:commands markers.
//
// Usage, from the repository root:
//
//	go run ./tools/docgen
//
// The golden test in this package (go test ./...) fails when the committed
// files differ from what this tool generates.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/isaias-alt/vexillum/internal/cli"
)

const (
	referenceDir = "site/content/docs/reference/cli"
	readmePath   = "README.md"

	readmeStart = "<!-- docgen:commands:start -->"
	readmeEnd   = "<!-- docgen:commands:end -->"
)

func main() {
	root := flag.String("root", ".", "repository root to write into")
	flag.Parse()

	if err := write(*root); err != nil {
		fmt.Fprintf(os.Stderr, "docgen: %v\n", err)
		os.Exit(1)
	}
}

// generate returns the full desired content of every generated file, keyed
// by slash-separated path relative to the repository root. root is only
// read, to splice the README table into the committed README.
func generate(root string) (map[string]string, error) {
	files := map[string]string{}
	cmds := cli.Commands()

	for _, c := range cmds {
		files[referenceDir+"/"+c.Name+".mdx"] = commandPage(c)
	}
	files[referenceDir+"/index.mdx"] = indexPage(cmds)

	readme, err := os.ReadFile(filepath.Join(root, readmePath))
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", readmePath, err)
	}
	updated, err := spliceReadme(string(readme), commandTable(cmds))
	if err != nil {
		return nil, fmt.Errorf("%s: %w", readmePath, err)
	}
	files[readmePath] = updated
	return files, nil
}

// write generates everything and writes it under root, removing any stale
// page for a command that no longer exists.
func write(root string) error {
	files, err := generate(root)
	if err != nil {
		return err
	}

	for rel, content := range files {
		path := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("create directory for %s: %w", rel, err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", rel, err)
		}
	}

	stale, err := staleFiles(root, files)
	if err != nil {
		return err
	}
	for _, rel := range stale {
		if err := os.Remove(filepath.Join(root, filepath.FromSlash(rel))); err != nil {
			return fmt.Errorf("remove stale %s: %w", rel, err)
		}
	}
	return nil
}

// staleFiles lists .mdx files in the reference directory that the
// generator no longer produces.
func staleFiles(root string, files map[string]string) ([]string, error) {
	entries, err := os.ReadDir(filepath.Join(root, filepath.FromSlash(referenceDir)))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read %s: %w", referenceDir, err)
	}
	var stale []string
	for _, e := range entries {
		rel := referenceDir + "/" + e.Name()
		if _, ok := files[rel]; !ok && strings.HasSuffix(e.Name(), ".mdx") {
			stale = append(stale, rel)
		}
	}
	sort.Strings(stale)
	return stale, nil
}

const generatedNotice = "{/* Generated by tools/docgen from internal/cli/commands.go. Do not edit by hand: run `go run ./tools/docgen`. */}"

func commandPage(c cli.Command) string {
	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "title: %s\n", strconv.Quote("vexillum "+c.Name))
	fmt.Fprintf(&b, "description: %s\n", strconv.Quote(c.Summary))
	b.WriteString("---\n\n")
	b.WriteString(generatedNotice + "\n\n")

	fence := codeFence(c.Usage)
	b.WriteString(fence + "text\n")
	b.WriteString(strings.TrimRight(c.Usage, "\n") + "\n")
	b.WriteString(fence + "\n")
	return b.String()
}

func indexPage(cmds []cli.Command) string {
	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("title: \"CLI reference\"\n")
	b.WriteString("description: \"Every vexillum command, with its full usage.\"\n")
	b.WriteString("---\n\n")
	b.WriteString(generatedNotice + "\n\n")
	b.WriteString("Run `vexillum --help` for this list, or `vexillum <command> -h` for a single command.\n\n")
	b.WriteString("| Command | Description |\n| --- | --- |\n")
	for _, c := range cmds {
		fmt.Fprintf(&b, "| [`vexillum %s`](/docs/reference/cli/%s) | %s |\n",
			c.Name, c.Name, escapeMDX(c.Summary))
	}
	return b.String()
}

func commandTable(cmds []cli.Command) string {
	var b strings.Builder
	b.WriteString("| Command | Description |\n| --- | --- |\n")
	for _, c := range cmds {
		fmt.Fprintf(&b, "| `vexillum %s` | %s |\n", c.Name, strings.ReplaceAll(c.Summary, "|", `\|`))
	}
	return b.String()
}

// spliceReadme replaces whatever sits between the docgen markers in readme
// with table, leaving the markers themselves in place.
func spliceReadme(readme, table string) (string, error) {
	start := strings.Index(readme, readmeStart)
	end := strings.Index(readme, readmeEnd)
	if start < 0 || end < 0 || end < start {
		return "", fmt.Errorf("missing or misordered %s / %s markers", readmeStart, readmeEnd)
	}
	return readme[:start+len(readmeStart)] + "\n" + table + readme[end:], nil
}

// codeFence returns a backtick fence longer than any backtick run in s, so
// usage text can never terminate its own code block early.
func codeFence(s string) string {
	longest, run := 0, 0
	for _, r := range s {
		if r == '`' {
			run++
			if run > longest {
				longest = run
			}
		} else {
			run = 0
		}
	}
	if longest < 3 {
		longest = 2
	}
	return strings.Repeat("`", longest+1)
}

// escapeMDX escapes the characters MDX would parse as JSX or expressions
// in prose.
func escapeMDX(s string) string {
	return strings.NewReplacer("<", "&lt;", "{", "&#123;", "|", `\|`).Replace(s)
}
