// Command docgen renders vexillum's command reference from the registry in
// internal/cli, so the docs can't drift from the CLI.
//
// It is a dev-only tool, like tools/whiteboard-bundle: run it by hand when a
// command changes, never as part of the installed binary. It writes:
//
//   - site/content/docs/en/reference/cli/<command>.mdx, one page per command
//     (usage verbatim in a code block), plus an index.mdx and a meta.json
//     that keeps the pages in registry order,
//   - site/content/docs/es/reference/cli/index.mdx and meta.json: the
//     Spanish tree gets only the index. A command's usage is the binary's
//     own English output, so the Spanish site reuses the English command
//     pages (the docs loader falls back to English for a page a locale
//     does not have) and this index links to them under /es/docs. Nothing
//     else in the Spanish tree is generated or ever removed, so a command
//     page translated by hand there is safe, and
//   - the command table in README.md, between the docgen:commands markers.
//
// Usage, from the repository root:
//
//	go run ./tools/docgen
//
// The golden test in this package (go test ./...) fails when the committed
// files differ from what this tool generates.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/isaias-alt/vexillum/internal/atomicfile"
	"github.com/isaias-alt/vexillum/internal/cli"
	"github.com/isaias-alt/vexillum/internal/cmdname"
)

const (
	referenceDir   = "site/content/docs/en/reference/cli"
	referenceDirES = "site/content/docs/es/reference/cli"
	readmePath     = "README.md"

	readmeStart = "<!-- docgen:commands:start -->"
	readmeEnd   = "<!-- docgen:commands:end -->"
)

func main() {
	root := flag.String("root", ".", "repository root to write into")
	flag.Parse()

	if err := write(*root); err != nil {
		fmt.Fprintf(os.Stderr, "docgen: %v\n", err)
		os.Exit(1)
	}
}

// generate returns the full desired content of every generated file, keyed
// by slash-separated path relative to the repository root. root is only
// read, to splice the README table into the committed README.
func generate(root string) (map[string]string, error) {
	files := map[string]string{}
	cmds := cli.Commands()

	for _, c := range cmds {
		files[referenceDir+"/"+c.Name+".mdx"] = commandPage(c)
	}
	files[referenceDir+"/index.mdx"] = indexPage(cmds, localeEN)
	files[referenceDir+"/meta.json"] = metaFile(cmds)
	files[referenceDirES+"/index.mdx"] = indexPage(cmds, localeES)
	files[referenceDirES+"/meta.json"] = metaFile(cmds)

	readme, err := os.ReadFile(filepath.Join(root, readmePath))
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", readmePath, err)
	}
	updated, err := spliceReadme(string(readme), commandTable(cmds))
	if err != nil {
		return nil, fmt.Errorf("%s: %w", readmePath, err)
	}
	files[readmePath] = updated
	return files, nil
}

// write generates everything in memory first, so a generation error leaves
// the tree untouched, then writes each file atomically (temp + rename) and
// finally removes stale pages. Stale cleanup covers only what the generator
// owns: .mdx files directly inside referenceDir (the English tree).
// Nothing else under site/ is ever deleted, the Spanish tree included.
func write(root string) error {
	files, err := generate(root)
	if err != nil {
		return err
	}
	stale, err := staleFiles(root, files)
	if err != nil {
		return err
	}

	for rel, content := range files {
		path := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("create directory for %s: %w", rel, err)
		}
		if err := atomicfile.Write(path, []byte(content)); err != nil {
			return fmt.Errorf("write %s: %w", rel, err)
		}
	}
	for _, rel := range stale {
		if err := os.Remove(filepath.Join(root, filepath.FromSlash(rel))); err != nil {
			return fmt.Errorf("remove stale %s: %w", rel, err)
		}
	}
	return nil
}

// staleFiles lists the .mdx files directly in referenceDir (the only files
// the generator owns there) that it no longer produces.
func staleFiles(root string, files map[string]string) ([]string, error) {
	entries, err := os.ReadDir(filepath.Join(root, filepath.FromSlash(referenceDir)))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read %s: %w", referenceDir, err)
	}
	var stale []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		rel := referenceDir + "/" + e.Name()
		if _, ok := files[rel]; !ok && strings.HasSuffix(e.Name(), ".mdx") {
			stale = append(stale, rel)
		}
	}
	sort.Strings(stale)
	return stale, nil
}

const generatedNotice = "{/* Generated by tools/docgen from internal/cli/commands.go. Do not edit by hand: run `go run ./tools/docgen`. */}"

func commandPage(c cli.Command) string {
	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "title: %s\n", yamlString(cmdname.Name+" "+c.Name))
	fmt.Fprintf(&b, "description: %s\n", yamlString(c.Summary))
	b.WriteString("---\n\n")
	b.WriteString(generatedNotice + "\n\n")

	fence := codeFence(c.Usage)
	b.WriteString(fence + "text\n")
	b.WriteString(strings.TrimRight(c.Usage, "\n") + "\n")
	b.WriteString(fence + "\n")
	return b.String()
}

// locale holds the few strings, and the URL prefix, that differ between the
// generated index pages. The command summaries and usage are the binary's
// own English text in every locale.
type locale struct {
	urlPrefix, title, description, intro, commandHeader, descriptionHeader string
}

var (
	localeEN = locale{
		urlPrefix:         "/docs",
		title:             "CLI reference",
		description:       "Every vexillum command, with its full usage.",
		intro:             "Run `" + cmdname.Name + " --help` for this list, or `" + cmdname.Name + " <command> -h` for a single command.",
		commandHeader:     "Command",
		descriptionHeader: "Description",
	}
	localeES = locale{
		urlPrefix:   "/es/docs",
		title:       "Referencia del CLI",
		description: "Todos los comandos de vexillum, con su uso completo.",
		intro: "Esta referencia se genera desde el binario y se mantiene en inglés: cada página es la salida literal de `" + cmdname.Name + " <command> -h`. " +
			"Ejecutá `" + cmdname.Name + " --help` para esta lista, o `" + cmdname.Name + " <command> -h` para un solo comando.",
		commandHeader:     "Comando",
		descriptionHeader: "Descripción",
	}
)

func indexPage(cmds []cli.Command, l locale) string {
	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "title: %s\n", yamlString(l.title))
	fmt.Fprintf(&b, "description: %s\n", yamlString(l.description))
	b.WriteString("---\n\n")
	b.WriteString(generatedNotice + "\n\n")
	b.WriteString(l.intro + "\n\n")
	fmt.Fprintf(&b, "| %s | %s |\n| --- | --- |\n", l.commandHeader, l.descriptionHeader)
	for _, c := range cmds {
		fmt.Fprintf(&b, "| [`"+cmdname.Name+" %s`](%s/reference/cli/%s) | %s |\n",
			c.Name, l.urlPrefix, c.Name, escapeMDX(c.Summary))
	}
	return b.String()
}

// metaFile is the Fumadocs folder metadata: it keeps the sidebar in
// registry order (the index first) instead of alphabetical.
func metaFile(cmds []cli.Command) string {
	pages := []string{strconv.Quote("index")}
	for _, c := range cmds {
		pages = append(pages, strconv.Quote(c.Name))
	}
	return "{\n  \"title\": \"CLI\",\n  \"pages\": [" + strings.Join(pages, ", ") + "]\n}\n"
}

func commandTable(cmds []cli.Command) string {
	var b strings.Builder
	b.WriteString("| Command | Description |\n| --- | --- |\n")
	for _, c := range cmds {
		fmt.Fprintf(&b, "| `"+cmdname.Name+" %s` | %s |\n", c.Name, escapeMarkdown(c.Summary))
	}
	return b.String()
}

// spliceReadme replaces whatever sits between the docgen markers in readme
// with table, leaving the markers themselves in place.
func spliceReadme(readme, table string) (string, error) {
	start := strings.Index(readme, readmeStart)
	end := strings.Index(readme, readmeEnd)
	if start < 0 || end < 0 || end < start {
		return "", fmt.Errorf("missing or misordered %s / %s markers", readmeStart, readmeEnd)
	}
	return readme[:start+len(readmeStart)] + "\n" + table + readme[end:], nil
}

// codeFence returns a backtick fence longer than any backtick run in s, so
// usage text can never terminate its own code block early.
func codeFence(s string) string {
	longest, run := 0, 0
	for _, r := range s {
		if r == '`' {
			run++
			if run > longest {
				longest = run
			}
		} else {
			run = 0
		}
	}
	if longest < 3 {
		longest = 2
	}
	return strings.Repeat("`", longest+1)
}

// Escaping lives here, one helper per output format, so no call site
// hand-rolls it. Both use backslash escapes, which GFM and MDX both honor.

const markdownSpecials = "\\`*_[]<>|&#"

// escapeMarkdown makes s literal text inside a GFM table cell (README).
func escapeMarkdown(s string) string {
	return escapeChars(s, markdownSpecials)
}

// escapeMDX makes s literal text inside MDX prose or a table cell: the
// Markdown set plus braces, which MDX parses as expressions.
func escapeMDX(s string) string {
	return escapeChars(s, markdownSpecials+"{}")
}

// yamlString renders s as a double-quoted YAML scalar for frontmatter.
// strconv.Quote output (\", \\, \n, \uXXXX) is valid YAML double-quoted
// syntax.
func yamlString(s string) string {
	return strconv.Quote(s)
}

func escapeChars(s, specials string) string {
	var b strings.Builder
	for _, r := range s {
		if strings.ContainsRune(specials, r) {
			b.WriteByte('\\')
		}
		b.WriteRune(r)
	}
	return b.String()
}
