package main

import (
	"fmt"
	"path"
	"strconv"
	"strings"

	"github.com/isaias-alt/vexillum/internal/cmdname"
	"github.com/isaias-alt/vexillum/internal/commander"
	"github.com/isaias-alt/vexillum/internal/slot"
	"github.com/isaias-alt/vexillum/skills"
)

// The skills and slot-block pages are generated from the same embedded files
// the binary writes into a project (skills/ and internal/commander), so the
// docs cannot drift from what `vx init` installs. Both locales get a page:
// the prose around the content is translated, the content itself (skills and
// the English core) is shown verbatim.
const (
	skillsDirEN = "site/content/docs/en/reference/skills"
	skillsDirES = "site/content/docs/es/reference/skills"
	slotPageEN  = "site/content/docs/en/reference/slot-block.mdx"
	slotPageES  = "site/content/docs/es/reference/slot-block.mdx"
)

const skillsNotice = "{/* Generated by tools/docgen from the embedded skills (skills/) and the commander core (internal/commander). Do not edit by hand: run `go run ./tools/docgen`. */}"

type contentLocale struct {
	urlPrefix string
	dir       string

	skillsIndexTitle, skillsIndexDescription, skillsIndexIntro string
	skillHeader, descriptionHeader                             string
	skillTitle                                                 func(name string) string
	skillDescription                                           func(name string) string
	skillIntro                                                 func(name, hash string, n int) string
	fileHeading                                                func(rel string) string

	slotTitle, slotDescription, slotIntro string
	slotEN, slotES                        string
	slotNote                              string
}

var (
	contentEN = contentLocale{
		urlPrefix: "/docs",
		dir:       skillsDirEN,

		skillsIndexTitle:       "Skills content",
		skillsIndexDescription: "The full text of the skills vexillum installs, generated from the files embedded in the binary.",
		skillsIndexIntro: "These pages show every file of the three first-party skills exactly as `" + cmdname.Name + " init` writes them. " +
			"They are generated from the files embedded in the binary, so they cannot drift. For what a skill is and where it is installed, see [Skills](/docs/concepts/skills).",
		skillHeader:       "Skill",
		descriptionHeader: "Description",
		skillTitle:        func(name string) string { return "Skill: " + name },
		skillDescription: func(name string) string {
			return "The full text of the " + name + " skill, generated from the files embedded in the vx binary."
		},
		skillIntro: func(name, hash string, n int) string {
			return fmt.Sprintf("This is the full content of the `%s` skill: %d %s, shown verbatim. "+
				"`"+cmdname.Name+" init` writes them to `.claude/skills/%s/` (or `~/.claude/skills/%s/` with `--global`), and `"+cmdname.Name+" upgrade` keeps them current. "+
				"Content hash: `%s`. See [Skills](/docs/concepts/skills) for the overview.",
				name, n, plural(n, "file", "files"), name, name, hash[:12])
		},
		fileHeading: func(rel string) string { return "`" + rel + "`" },

		slotTitle:       "AGENTS.md block",
		slotDescription: "The exact block vexillum keeps in your AGENTS.md, in English and Spanish, generated from the binary.",
		slotIntro: "This is the block `" + cmdname.Name + " init` writes into your `AGENTS.md`, rendered by the same code the binary runs, markers and hash included. " +
			"For how each part works, see [The AGENTS.md slot](/docs/concepts/agents-md-slot).",
		slotEN:   "English",
		slotES:   "Spanish",
		slotNote: "Which language is written follows the language detected in your `AGENTS.md`, or `--lang`. The hash differs per language because it is computed over the body.",
	}
	contentES = contentLocale{
		urlPrefix: "/es/docs",
		dir:       skillsDirES,

		skillsIndexTitle:       "Contenido de las skills",
		skillsIndexDescription: "El texto completo de las skills que instala vexillum, generado desde los archivos embebidos en el binario.",
		skillsIndexIntro: "Estas páginas muestran cada archivo de las tres skills first-party tal como los escribe `" + cmdname.Name + " init`. " +
			"Se generan desde los archivos embebidos en el binario, así que no se desfasan. Las skills están en inglés, por eso el contenido se muestra en inglés. " +
			"Para saber qué es una skill y dónde se instala, mirá [Skills](/es/docs/concepts/skills).",
		skillHeader:       "Skill",
		descriptionHeader: "Descripción",
		skillTitle:        func(name string) string { return "Skill: " + name },
		skillDescription: func(name string) string {
			return "El texto completo de la skill " + name + ", generado desde los archivos embebidos en el binario vx."
		},
		skillIntro: func(name, hash string, n int) string {
			return fmt.Sprintf("Este es el contenido completo de la skill `%s`: %d %s, mostrados tal cual y en inglés. "+
				"`"+cmdname.Name+" init` los escribe en `.claude/skills/%s/` (o en `~/.claude/skills/%s/` con `--global`), y `"+cmdname.Name+" upgrade` los mantiene al día. "+
				"Hash del contenido: `%s`. Mirá [Skills](/es/docs/concepts/skills) para la visión general.",
				name, n, plural(n, "archivo", "archivos"), name, name, hash[:12])
		},
		fileHeading: func(rel string) string { return "`" + rel + "`" },

		slotTitle:       "Bloque de AGENTS.md",
		slotDescription: "El bloque exacto que vexillum mantiene en tu AGENTS.md, en inglés y en español, generado desde el binario.",
		slotIntro: "Este es el bloque que `" + cmdname.Name + " init` escribe en tu `AGENTS.md`, renderizado por el mismo código que corre el binario, con marcadores y hash incluidos. " +
			"Para entender cada parte, mirá [El slot de AGENTS.md](/es/docs/concepts/agents-md-slot).",
		slotEN:   "Inglés",
		slotES:   "Español",
		slotNote: "El idioma que se escribe sigue el idioma detectado en tu `AGENTS.md`, o `--lang`. El hash cambia por idioma porque se calcula sobre el cuerpo.",
	}
)

func plural(n int, one, many string) string {
	if n == 1 {
		return one
	}
	return many
}

// contentFiles adds the skills and slot-block pages for both locales.
func contentFiles(files map[string]string) error {
	for _, l := range []contentLocale{contentEN, contentES} {
		names := skills.Names()
		for _, name := range names {
			page, err := skillPage(name, l)
			if err != nil {
				return err
			}
			files[l.dir+"/"+name+".mdx"] = page
		}
		idx, err := skillsIndexPage(names, l)
		if err != nil {
			return err
		}
		files[l.dir+"/index.mdx"] = idx
		files[l.dir+"/meta.json"] = skillsMeta(names)
	}
	for l, p := range map[string]contentLocale{slotPageEN: contentEN, slotPageES: contentES} {
		page, err := slotBlockPage(p)
		if err != nil {
			return err
		}
		files[l] = page
	}
	return nil
}

func frontmatter(title, description string) string {
	return "---\ntitle: " + yamlString(title) + "\ndescription: " + yamlString(description) + "\n---\n\n"
}

// skillDescription extracts the description from a SKILL.md's frontmatter.
func skillDescription(skillMD string) string {
	lines := strings.Split(skillMD, "\n")
	if len(lines) == 0 || strings.TrimSpace(lines[0]) != "---" {
		return ""
	}
	for _, ln := range lines[1:] {
		if strings.TrimSpace(ln) == "---" {
			break
		}
		if v, ok := strings.CutPrefix(ln, "description:"); ok {
			return strings.TrimSpace(v)
		}
	}
	return ""
}

// firstSentence keeps index rows short: the description up to its first
// period followed by a space.
func firstSentence(s string) string {
	if i := strings.Index(s, ". "); i >= 0 {
		return s[:i+1]
	}
	return s
}

func skillPage(name string, l contentLocale) (string, error) {
	files, err := skills.Files(name)
	if err != nil {
		return "", err
	}
	hash, err := skills.Hash(name)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString(frontmatter(l.skillTitle(name), l.skillDescription(name)))
	b.WriteString(skillsNotice + "\n\n")
	b.WriteString(l.skillIntro(name, hash, len(files)) + "\n\n")
	for _, f := range files {
		b.WriteString("## " + l.fileHeading(path.Clean(f.Path)) + "\n\n")
		text := strings.TrimRight(string(f.Content), "\n")
		fence := codeFence(text)
		b.WriteString(fence + "markdown\n" + text + "\n" + fence + "\n\n")
	}
	return strings.TrimRight(b.String(), "\n") + "\n", nil
}

func skillsIndexPage(names []string, l contentLocale) (string, error) {
	var b strings.Builder
	b.WriteString(frontmatter(l.skillsIndexTitle, l.skillsIndexDescription))
	b.WriteString(skillsNotice + "\n\n")
	b.WriteString(l.skillsIndexIntro + "\n\n")
	fmt.Fprintf(&b, "| %s | %s |\n| --- | --- |\n", l.skillHeader, l.descriptionHeader)
	for _, name := range names {
		data, err := skills.ReadFile(name, "SKILL.md")
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "| [`%s`](%s/reference/skills/%s) | %s |\n",
			name, l.urlPrefix, name, escapeMDX(firstSentence(skillDescription(string(data)))))
	}
	return b.String(), nil
}

func skillsMeta(names []string) string {
	pages := []string{strconv.Quote("index")}
	for _, n := range names {
		pages = append(pages, strconv.Quote(n))
	}
	return "{\n  \"title\": \"Skills content\",\n  \"pages\": [" + strings.Join(pages, ", ") + "]\n}\n"
}

func slotBlockPage(l contentLocale) (string, error) {
	var b strings.Builder
	b.WriteString(frontmatter(l.slotTitle, l.slotDescription))
	b.WriteString(skillsNotice + "\n\n")
	b.WriteString(l.slotIntro + "\n\n")
	for _, s := range []struct {
		heading string
		lang    string
	}{{l.slotEN, commander.LangEN}, {l.slotES, commander.LangES}} {
		body, err := commander.Core(s.lang)
		if err != nil {
			return "", err
		}
		block := slot.Render(body)
		fence := codeFence(block)
		b.WriteString("## " + s.heading + "\n\n")
		b.WriteString(fence + "markdown\n" + strings.TrimRight(block, "\n") + "\n" + fence + "\n\n")
	}
	b.WriteString(l.slotNote + "\n")
	return b.String(), nil
}
