blank_issues_enabled: true
contact_links:
  - name: Contributing guide
    url: https://github.com/isaias-alt/vexillum/blob/canary/CONTRIBUTING.md
    about: How to report a bug, propose a feature or send a pull request
